-- Starting over, on purpose.
--
-- Run it in Neon's SQL editor. Nothing here is reversible, and the engine
-- recreates every table it needs at boot, so nothing has to be put back.
--
-- The tables fall into two groups and the difference matters more than it
-- used to:
--
--   STATE  — this IS the system. Erasing it is the reset.
--   CACHE  — only ever an optimisation. Erasing it costs one slow cycle.
--
-- Two things in the STATE group are worth stopping on before you run this:
--
--   `fills` is no longer just a history. Realised profit and the COMMON FUND
--   are both derived from it, so truncating it does not erase a record — it
--   erases the money you made, and the allocator goes back to believing it has
--   exactly the capital in OPERADOR_CAPITAL_USD.
--
--   `blacklist` holds the death-exit verdicts. Emptying it lets the scanner
--   offer you a token that was already proven to be a rug.

-- NOTHING IN THIS FILE RUNS AS IT STANDS. Uncomment the ONE block you mean.
--
-- It did not used to be that way, and it cost real money: the destructive
-- variant was the only uncommented statement, so pasting the file into Neon's
-- editor wiped `fills` — and `fills` is not a log, it is where the realised
-- profit and the common fund are DERIVED from. A dollar of profit disappeared
-- that way, from someone who had been told to run the other one.
--
-- A destructive script whose default is the worst option is a trap, however
-- well it is commented above the line.

-- ── Everything. A genuine fresh start. ──────────────────────────────────────
-- TRUNCATE TABLE positions, fills, checkpoint, blacklist, alerts;
-- TRUNCATE TABLE scans, pool_discovery, pool_history, token_security, pool_quiet;

-- ── Or: start the book over, KEEP what was learned ──────────────────────────
--
-- Positions and their ladders go; the profit history, the death-exit verdicts
-- and every cached measurement stay. This is usually what "let's start clean"
-- actually means: a fresh book, not an engine with amnesia.
--
-- TRUNCATE TABLE positions, checkpoint;
--
-- This is the right one after a run that filled the book with tokens the engine
-- could not watch. The damage is in `positions`; the caches are what make the
-- next scan fast, and the fills are the profit. Throwing all three away to fix
-- one of them costs a fifteen-minute cold sweep and the realised P&L for
-- nothing.
--
-- BUT IT IS NOT FREE, and the cost was found the hard way. Profit on screen is
-- `cobrada + sin cobrar − costos`:
--
--   COBRADA survives. It is derived by walking the whole `fills` table, which
--   this leaves alone.
--
--   SIN COBRAR does not. Unrealised gain exists only while the position it sits
--   on does, so deleting the positions deletes it — a dollar vanished exactly
--   that way, and it looked like a bug.
--
--   And the deleted positions' fills STAY, with buys and no matching sells. The
--   capital inside them is then orphaned: neither realised nor unrealised, just
--   absent. The paper tokens are still "held" by a position that no longer
--   exists.
--
-- So: cheap when the book is mostly reservations that never bought, and
-- genuinely lossy when it is not. Download the Registro first if the history
-- matters.

-- ── Or: only forget the measurements ────────────────────────────────────────
--
-- After changing a gate or a scoring policy, when the cached verdicts were
-- reached under rules that no longer apply. Costs one slow cycle and nothing
-- else — every row here is rebuilt from the providers.
--
-- TRUNCATE TABLE scans, pool_discovery, pool_history, token_security, pool_quiet;
